# Dependencies
markdown: kramdown
highlighter: rouge
kramdown:
  auto_ids: true

permalink: pretty

source: '.'
destination: './_site'
encoding: UTF-8
exclude:
  - .git/
  - .github/
  - .idea/
  - src/
#  - docs/componenti/
#  - docs/form/
#  - docs/utilities/
#  - docs/esempi/
#  - docs/organizzare-i-contenuti/
  - vendor
  - node_modules/
  - AUTHORS
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - yarn.lock
  - package.json
  - package-lock.json
  - README.md
  - gulpfile.js

plugins:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-toc

toc:
  max_level: 3

# Social
title:              'Bootstrap Lombardia'
description:        'Bootstrap Lombardia è una customizzazione di Boostrap Italia per la creazione di applicazioni web per la Regione Lombardia nel pieno rispetto delle Linee guida di design per i servizi web della PA'
authors:            'Azienda Regionale Innovazione e Acquisti'
authors_url:        'https://www.ariaspa.it/'
authors_agid: "Agenzia per l'Italia Digitale"
authors_agid_url: 'https://www.agid.gov.it/'
social_card_path: '/docs/assets/img/favicons/social-card.png'
social_logo_path: '/docs/assets/img/favicons/android-chrome-192x192.png'
repo:               'https://github.com/RegioneLombardia/bootstrap-lombardia/'
developers: 'https://developers.italia.it/'
slack: 'https://slack.developers.italia.it/'
twitter: 'https://twitter.com/designersITA'
twitter_handle: '@designersITA'

# Versions
current_version:		0.3.5
bootstrap-italia_version:		1.6.3
bootstrap_version: 4.6.1
bootstrap_minor: 4.5

# Analytics
ga_property: 'UA-114758441-1'

# CDN links
cdn:
  jquery: '<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" crossorigin="anonymous"></script>'
  popper: '<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.1/umd/popper.min.js" crossorigin="anonymous"></script>'
